[server]
# Automatically rerun script when the file is modified on disk.
# Default: false
runOnSave = true

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 50

[theme]

# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
# base = "dark"

# Primary accent color for interactive elements.
# primaryColor =

# Background color for the main content area.
backgroundColor = "#000000"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#000000"

# Color used for almost all text.
textColor = "FFFFFF"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# font =

[browser]
gatherUsageStats = false